service: adminlte

useDotenv: true

plugins:
  - serverless-offline

provider: 
  name: aws
  runtime: nodejs18.x
  environment:
    DB_HOST= ${env:DB_HOST}
    DB_PORT= ${env:DB_PORT}
    DB_USERNAME= ${env:DB_USERNAME}
    DB_PASSWORD= ${env:DB_PASSWORD}
    DB_NAME= ${env:DB_NAME}
    PORT= ${env:PORT}
    SECRET= ${env:SECRET}
    DOMAIN= ${env:DOMAIN}

functions: 
  main: 
    handler: dist/src/serverless.handler
    events: 
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'